name: Acquire Citadel Actions Cache
on:
  workflow_dispatch:
jobs:
  build:
    name: Acquire Citadel Actions Cache
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Mark Library folder to be preserved
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-Android-Experimental
          restore-keys: |
            Library-Android
      - name: Download custom Docker image
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker pull josiahjack/citadel-ci:ubuntu-2020.3.48f1-android-3
      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: Citadel_DevBuild_AndroidExperimental
          path: |
            Library
          if-no-files-found: error
