name: Fresh Build
on:
  # Manual runs only.
  workflow_dispatch:
jobs:
  build:
    name: Citadel Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX       # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64   # Build a Linux 64-bit standalone.
        dockerImage:
          - mac-mono
          - windows-mono
          - linux-il2cpp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run custom image build
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          chmod +x ./build.sh
          ./build.sh
      - name: Build game
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
          customImage: josiahjack/citadel-ci:ubuntu-2019.4.35f1-${{ matrix.dockerImage }}-1
          allowDirtyBuild: true

      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: Citadel_DevBuild_${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          if-no-files-found: error
