name: Fresh Build
on:
  # Manual runs only.
  workflow_dispatch:
jobs:
  build:
    name: Citadel Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Unzip blender and add to path and associate blend files
        run: |
          unzip ${GITHUB_WORKSPACE}/BuildTools/blender2.76b/blender.zip;
          echo "$PATH"
          ls
          export "PATH=$PATH:${GITHUB_WORKSPACE}"
          echo "$PATH"
          which blender
          xdg-mime default ${GITHUB_WORKSPACE}/BuildTools/blender2.76b/userapp-blender.desktop application/x-blender
          xdg-mime query default application/x-blender
          blender --version

      # No caching in case there is an importing issue.
      # The Library folder will be rebuilt.  This will take a while!
      - name: Build game
        id: buildStep
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: Citadel_DevBuild
          versioning: Semantic
          allowDirtyBuild: true
      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: Citadel_DevBuild_${{ matrix.targetPlatform }}
          path: build/Citadel_DevBuild_${{ matrix.targetPlatform }}
