name: Fresh Build
on:
  # Manual runs only.
  workflow_dispatch:
jobs:
  build:
    name: Citadel Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX       # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64   # Build a Linux 64-bit standalone.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # This project requires Blender 2.76b to be installed for .blend files to be imported
      # as .fbx files prior to builds or else no models will be included in the build.
      - name: Install blender
        run: |
          sudo apt-get update
          sudo apt-get install blender
          #unzip ${GITHUB_WORKSPACE}/BuildTools/blender2.76b/blender.zip;
          #echo "$PATH"
          #ls
          #mv ${GITHUB_WORKSPACE}/blender ${GITHUB_WORKSPACE}/BuildTools/blender2.76b/blender
          #sudo apt-get install libglu1
          #export "PATH=$PATH:${GITHUB_WORKSPACE}/BuildTools/blender2.76b"
          #echo "$PATH" >> $GITHUB_PATH
          #echo "PATH=${GITHUB_PATH}" >> $GITHUB_ENV
          #echo "Path set: $PATH"
          #which blender
          # xdg-mime default ${GITHUB_WORKSPACE}/BuildTools/blender2.76b/userapp-blender.desktop application/x-blender
          echo "Confirm Blender installation: "
          xdg-mime query default application/x-blender
          blender --version

      # No caching in case there is an importing issue.
      # The Library folder will be rebuilt.  This will take a while!
      - name: Build game
        id: buildStep
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
          allowDirtyBuild: true
      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: Citadel_DevBuild_${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
          if-no-files-found: error
