name: A Build
on:
  workflow_dispatch:
jobs:
  build:
    name: Citadel Build Android Experimental
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run custom image build
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          chmod +x ./build_a.sh
          ./build.sh push_docker
      - name: Download custom Docker image
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker pull josiahjack/citadel-ci:ubuntu-2020.3.48f1-android-3

      - name: Build game
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          versioning: Semantic
          customImage: josiahjack/citadel-ci:ubuntu-2020.3.48f1-android-3
          allowDirtyBuild: true

      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: Citadel_DevBuild_Android
          path: build/Android
          if-no-files-found: error
