name: Fresh Build
on:
  # Manual runs only.
  workflow_dispatch:
jobs:
  build:
    name: Citadel Build ${{ matrix.plans.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        plans: [ {targetPlatform: StandaloneOSX, dockerImage: mac-mono}, {targetPlatform: StandaloneWindows64, dockerImage: windows-mono}, {targetPlatform: StandaloneLinux64, dockerImage: linux-il2cpp} ] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run custom image build
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          chmod +x ./build.sh
          ./build.sh

      - name: Unit Tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts

      - name: Build game
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.plans.targetPlatform }}
          versioning: Semantic
          customImage: josiahjack/citadel-ci:ubuntu-2019.4.35f1-${{ matrix.plans.dockerImage }}-1
          allowDirtyBuild: true

      - name: Upload built files
        uses: actions/upload-artifact@v2
        with:
          name: Citadel_DevBuild_${{ matrix.plans.targetPlatform }}
          path: build/${{ matrix.plans.targetPlatform }}
          if-no-files-found: error
