name: Fresh Build
on:
  # Manual runs only.
  workflow_dispatch:
jobs:
  build:
  
    name: Citadel Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX       # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64   # Build a Linux 64-bit standalone.
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install blender and build
      run: |
        sudo apt-get update
        sudo apt-get install blender
        echo "Confirm Blender installation: "
        xdg-mime query default application/x-blender
        blender --version
        gh workflow run build_unity.yml
