# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Manual runs only.
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Citadel Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Unzip blender zip
        run: unzip ${GITHUB_WORKSPACE}/BuildTools/blender2.76b/blender.zip
        
      - name: Setup symlink to blender
        run: sudo ln -s ${GITHUB_WORKSPACE}/BuildTools/blender2.76b/blender /usr/bin/blender

      - name: Check blender presence
        run: which blender

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Citadel_DevBuild_${{ matrix.targetPlatform }}
          path: build/Citadel_DevBuild_${{ matrix.targetPlatform }}
