name: Run Tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Citadel Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      #- name: Run custom image build for docker setup
      #  run: |
      #    echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      #    chmod +x ./build_unittest_docker.sh
      #    ./build_unittest_docker.sh push_docker
          
      - name: Download custom Docker image
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker pull josiahjack/citadel-ci:ubuntu-2020.3.48f1-linux-il2cpp-3

      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-StandaloneLinux64
          restore-keys: |
            Library-
      - name: Unit Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          customImage: josiahjack/citadel-ci:ubuntu-2020.3.48f1-linux-il2cpp-3
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results
          path: |
            artifacts
            Assets/StreamingAssets/sav7.txt
            Assets/StreamingAssets/Player.log
