name: Run Tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Citadel Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - test-project
        testMode:
          - editmode
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run custom image build for docker setup
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          chmod +x ./build_unittest_docker.sh
          ./build_unittest_docker.sh
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-Citadel
          restore-keys: |
            Library-
      - name: Unit Tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          customImage: josiahjack/citadel-ci:ubuntu-2019.4.35f1-linux-il2cpp-1
          projectPath: ${{ matrix.projectPath }}
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results
          path: artifacts
